CREATE TABLE `datiMercato` (
	`id` int AUTO_INCREMENT NOT NULL,
	`comune` varchar(100) NOT NULL,
	`localita` varchar(200),
	`prezzoMedioMq` int NOT NULL,
	`prezzoMinMq` int,
	`prezzoMaxMq` int,
	`trendAnnuale` varchar(20),
	`numeroAnnunci` int,
	`caratteristiche` text,
	`ultimoAggiornamento` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `datiMercato_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `valutazioni` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`comune` varchar(100) NOT NULL,
	`localita` varchar(200),
	`indirizzo` text,
	`distanzaMare` int,
	`tipologia` varchar(50) NOT NULL,
	`categoriaCatastale` varchar(10),
	`superficieAbitabile` int NOT NULL,
	`numeroCamere` int,
	`numeroBagni` int,
	`piano` varchar(50),
	`statoManutenzione` varchar(50),
	`annoCostruzione` int,
	`classeEnergetica` varchar(10),
	`hasGiardino` boolean DEFAULT false,
	`superficieGiardino` int,
	`tipoGiardino` varchar(50),
	`hasTerrazzo` boolean DEFAULT false,
	`superficieTerrazzo` int,
	`tipoTerrazzo` varchar(50),
	`hasCortile` boolean DEFAULT false,
	`superficieCortile` int,
	`hasCantina` boolean DEFAULT false,
	`superficieCantina` int,
	`hasPostoAuto` boolean DEFAULT false,
	`tipoPostoAuto` varchar(50),
	`numeroPostiAuto` int,
	`vistaMare` varchar(100),
	`esposizione` varchar(50),
	`tipoPosizione` varchar(100),
	`accessoMare` varchar(100),
	`servizi` json,
	`finiture` json,
	`valoreBase` int NOT NULL,
	`valorePertinenze` int NOT NULL,
	`valoreValorizzazioni` int NOT NULL,
	`valoreSvalutazioni` int NOT NULL,
	`valoreTotale` int NOT NULL,
	`valoreMin` int NOT NULL,
	`valoreMax` int NOT NULL,
	`prezzoMqZona` int NOT NULL,
	`immobiliSimiliZona` int,
	`livelloCompetitivita` varchar(50),
	`breakdownCalcolo` json,
	`consigli` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `valutazioni_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `valutazioni` ADD CONSTRAINT `valutazioni_userId_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;